version: '3.8'

services:
  app:
    container_name: "web-barcode-generator"
    build: .
    ports:
      - "8310:8310"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
